// <auto-generated />
// Vendored third-party source - excluded from code-style analysis via the auto-generated marker above.
// Vendored from the "ReflectObject" NuGet package (v1.0.2) by Tony Hallett -
// https://github.com/tonyhallett/ReflectObject - "A simple reflection wrapper for objects."
// The package had no newer release and is a single-author micro-dependency, so its source is
// inlined here (namespace kept as ReflectObject so the InternalTypes wrappers are unchanged).
// The same code already shipped inside the FCC VSIX as ReflectObject.dll.
using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;

namespace ReflectObject
{
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
    public class DelegatePropertyAttribute : Attribute
    {
    }

    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
    public class DoNotThrowMissingMemberAttribute : Attribute
    {
    }

    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = false)]
    public class DoNotThrowMissingMembersAttribute : Attribute
    {
    }

    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
    public class IgnoreAttribute : Attribute
    {
    }

    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
    public class ReflectFlagsAttribute : Attribute
    {
        public BindingFlags BindingFlags { get; }

        public ReflectFlagsAttribute(BindingFlags bindingFlags)
        {
            BindingFlags = bindingFlags;
        }
    }

    public class PropertyDoesNotExistException : Exception
    {
        public Type ReflectedType { get; }

        public string PropertyName { get; }

        public BindingFlags BindingFlags { get; }

        public PropertyDoesNotExistException(string message, Type reflectedType, string propertyName, BindingFlags bindingFlags)
            : base(message)
        {
            ReflectedType = reflectedType;
            PropertyName = propertyName;
            BindingFlags = bindingFlags;
        }

        public static PropertyDoesNotExistException Create(Type reflectedType, string propertyName, BindingFlags bindingFlags)
        {
            return new PropertyDoesNotExistException($"Property {propertyName} with binding flags {bindingFlags} does not exist on {reflectedType.FullName}", reflectedType, propertyName, bindingFlags);
        }
    }

    internal interface IPropertySetter
    {
        void Set(ReflectObjectProperties wrapper, object reflectedObject);
    }

    internal abstract class PropertySetterBase<TMember> : IPropertySetter where TMember : MemberInfo
    {
        protected readonly PropertyInfo ownProperty;
        protected readonly BindingFlags bindingFlags;
        protected readonly Type ownPropertyType;
        protected TMember reflectedMember;
        protected readonly Type reflectedType;
        private Action<object, object> ownPropertySetter;
        private bool throwOnMissingMember;

        private Action<object, object> OwnPropertySetter
        {
            get
            {
                if (ownPropertySetter == null)
                {
                    ownPropertySetter = PropertySetterHelper.BuildSetAccessor(ownProperty.GetSetMethod(nonPublic: true));
                }

                return ownPropertySetter;
            }
        }

        public PropertySetterBase(PropertyInfo ownProperty, BindingFlags bindingFlags, Type reflectedType)
        {
            this.ownProperty = ownProperty;
            this.bindingFlags = bindingFlags;
            this.reflectedType = reflectedType;
            ownPropertyType = ownProperty.PropertyType;
            SetThrowOnMissingMember();
        }

        private void SetThrowOnMissingMember()
        {
            if (ownProperty.DeclaringType.GetCustomAttribute<DoNotThrowMissingMembersAttribute>() != null)
            {
                throwOnMissingMember = false;
                return;
            }

            DoNotThrowMissingMemberAttribute customAttribute = ownProperty.GetCustomAttribute<DoNotThrowMissingMemberAttribute>();
            throwOnMissingMember = customAttribute == null;
        }

        public void Set(ReflectObjectProperties wrapper, object reflectedObject)
        {
            if (MemberExists())
            {
                object propertyValue = GetPropertyValue(wrapper, reflectedObject);
                if (propertyValue != null)
                {
                    OwnPropertySetter(wrapper, propertyValue);
                }
            }
        }

        protected abstract TMember GetMember(string memberName);

        protected abstract object GetPropertyValue(ReflectObjectProperties wrapper, object reflectedObject);

        private bool MemberExists()
        {
            string name = ownProperty.Name;
            reflectedMember = GetMember(name);
            if (reflectedMember == null && throwOnMissingMember)
            {
                throw PropertyDoesNotExistException.Create(reflectedType, name, bindingFlags);
            }

            return reflectedMember != null;
        }
    }

    internal class PropertySetter : PropertySetterBase<PropertyInfo>
    {
        private static readonly Type listType;
        private static readonly Type enumerableTTYpe;
        private static readonly MethodInfo createEnumerableMethodInfo;
        private Func<object, object> coerceValue;

        static PropertySetter()
        {
            listType = typeof(List<>);
            enumerableTTYpe = typeof(IEnumerable<>);
            createEnumerableMethodInfo = typeof(PropertySetter).GetMethod("CreateEnumerable", BindingFlags.Instance | BindingFlags.NonPublic);
        }

        public PropertySetter(PropertyInfo ownProperty, BindingFlags bindingFlags, Type reflectedType)
            : base(ownProperty, bindingFlags, reflectedType)
        {
        }

        protected override object GetPropertyValue(ReflectObjectProperties wrapper, object reflectedObject)
        {
            object obj = reflectedMember.GetValue(reflectedObject);
            if (obj != null)
            {
                obj = CoerceValue(obj);
            }

            return obj;
        }

        internal object Wrap(Type type, object toReflect)
        {
            return Activator.CreateInstance(type, toReflect);
        }

        private T WrapTyped<T>(object toReflect)
        {
            return (T)Wrap(typeof(T), toReflect);
        }

        private MethodInfo GetCreateEnumerableMethodInfo(Type type)
        {
            return createEnumerableMethodInfo.MakeGenericMethod(type);
        }

        private IEnumerable<T> CreateEnumerable<T>(IEnumerable value) where T : ReflectObjectProperties
        {
            IEnumerator enumerator = value.GetEnumerator();
            while (enumerator.MoveNext())
            {
                yield return (enumerator.Current == null) ? null : WrapTyped<T>(enumerator.Current);
            }
        }

        private object CoerceValue(object value)
        {
            if (coerceValue == null)
            {
                if (ReflectObjectProperties.IsReflectObjectPropertiesType(ownPropertyType))
                {
                    coerceValue = (object v) => Wrap(ownPropertyType, v);
                }
                else if (ownPropertyType.IsGenericType)
                {
                    Type[] genericArguments = ownPropertyType.GetGenericArguments();
                    Type genericArgument = genericArguments[0];
                    if (genericArguments.Length == 1 && ReflectObjectProperties.IsReflectObjectPropertiesType(genericArgument))
                    {
                        Type genericTypeDefinition = ownPropertyType.GetGenericTypeDefinition();
                        if (genericTypeDefinition == listType)
                        {
                            Type constructedListType = listType.MakeGenericType(genericArgument);
                            MethodInfo addMethod = constructedListType.GetMethod("Add");
                            coerceValue = delegate (object v)
                            {
                                object obj = Activator.CreateInstance(constructedListType);
                                IEnumerator enumerator = (v as IEnumerable).GetEnumerator();
                                while (enumerator.MoveNext())
                                {
                                    addMethod.Invoke(obj, new object[1] { (enumerator.Current == null) ? null : Wrap(genericArgument, enumerator.Current) });
                                }

                                return obj;
                            };
                        }
                        else if (genericTypeDefinition == enumerableTTYpe)
                        {
                            MethodInfo createEnumerable = GetCreateEnumerableMethodInfo(genericArgument);
                            coerceValue = (object v) => createEnumerable.Invoke(this, new object[1] { v });
                        }
                    }
                }

                if (coerceValue == null)
                {
                    coerceValue = (object v) => v;
                }
            }

            return coerceValue(value);
        }

        protected override PropertyInfo GetMember(string memberName)
        {
            return reflectedType.GetProperty(memberName, bindingFlags);
        }
    }

    internal class MethodSetter : PropertySetterBase<MethodInfo>
    {
        private readonly bool isAction;

        public MethodSetter(PropertyInfo ownProperty, bool isAction, BindingFlags bindingFlags, Type reflectedType)
            : base(ownProperty, bindingFlags, reflectedType)
        {
            this.isAction = isAction;
        }

        protected override object GetPropertyValue(ReflectObjectProperties wrapper, object reflectedObject)
        {
            return MethodWrapper.CreateDelegateWrapper(reflectedMember, reflectedObject, ownProperty.PropertyType, isAction);
        }

        protected override MethodInfo GetMember(string memberName)
        {
            Type[] genericTypeArguments = ownProperty.PropertyType.GenericTypeArguments;
            Type[] types = isAction ? genericTypeArguments : genericTypeArguments.Take(genericTypeArguments.Length - 1).ToArray();
            return reflectedType.GetMethod(memberName, bindingFlags, null, types, new ParameterModifier[0]);
        }
    }

    internal class MethodWrapper
    {
        private readonly MethodInfo wrapped;
        private readonly object owner;
        private static readonly Type ThisType = typeof(MethodWrapper);

        private static readonly List<MethodInfo> WrapFuncs = new List<MethodInfo>
        {
            ThisType.GetMethod("WrapFunc"),
            ThisType.GetMethod("WrapFunc1"),
            ThisType.GetMethod("WrapFunc2"),
            ThisType.GetMethod("WrapFunc3"),
            ThisType.GetMethod("WrapFunc4"),
            ThisType.GetMethod("WrapFunc5"),
            ThisType.GetMethod("WrapFunc6"),
            ThisType.GetMethod("WrapFunc7"),
            ThisType.GetMethod("WrapFunc8"),
        };

        private static readonly List<MethodInfo> ActionFuncs = new List<MethodInfo>
        {
            ThisType.GetMethod("WrapAction"),
            ThisType.GetMethod("WrapAction1"),
            ThisType.GetMethod("WrapAction2"),
            ThisType.GetMethod("WrapAction3"),
            ThisType.GetMethod("WrapAction4"),
            ThisType.GetMethod("WrapAction5"),
            ThisType.GetMethod("WrapAction6"),
            ThisType.GetMethod("WrapAction7"),
            ThisType.GetMethod("WrapAction8"),
        };

        public static Delegate CreateDelegateWrapper(MethodInfo wrappedMethod, object owner, Type funcOrActionType, bool isAction)
        {
            MethodWrapper firstArgument = new MethodWrapper(wrappedMethod, owner);
            Type[] genericArguments = funcOrActionType.GetGenericArguments();
            MethodInfo method = !isAction
                ? WrapFuncs[genericArguments.Length - 1].MakeGenericMethod(genericArguments)
                : (genericArguments.Length != 0 ? ActionFuncs[genericArguments.Length].MakeGenericMethod(genericArguments) : ActionFuncs[0]);
            return Delegate.CreateDelegate(funcOrActionType, firstArgument, method);
        }

        public MethodWrapper(MethodInfo wrapped, object owner)
        {
            this.wrapped = wrapped;
            this.owner = owner;
        }

        public TReturn WrapFunc<TReturn>()
        {
            return (TReturn)wrapped.Invoke(owner, new object[0]);
        }

        public TReturn WrapFunc1<T1, TReturn>(T1 t1)
        {
            return (TReturn)wrapped.Invoke(owner, new object[1] { t1 });
        }

        public TReturn WrapFunc2<T1, T2, TReturn>(T1 t1, T2 t2)
        {
            return (TReturn)wrapped.Invoke(owner, new object[2] { t1, t2 });
        }

        public TReturn WrapFunc3<T1, T2, T3, TReturn>(T1 t1, T2 t2, T3 t3)
        {
            return (TReturn)wrapped.Invoke(owner, new object[3] { t1, t2, t3 });
        }

        public TReturn WrapFunc4<T1, T2, T3, T4, TReturn>(T1 t1, T2 t2, T3 t3, T4 t4)
        {
            return (TReturn)wrapped.Invoke(owner, new object[4] { t1, t2, t3, t4 });
        }

        public TReturn WrapFunc5<T1, T2, T3, T4, T5, TReturn>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5)
        {
            return (TReturn)wrapped.Invoke(owner, new object[5] { t1, t2, t3, t4, t5 });
        }

        public TReturn WrapFunc6<T1, T2, T3, T4, T5, T6, TReturn>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6)
        {
            return (TReturn)wrapped.Invoke(owner, new object[6] { t1, t2, t3, t4, t5, t6 });
        }

        public TReturn WrapFunc7<T1, T2, T3, T4, T5, T6, T7, TReturn>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7)
        {
            return (TReturn)wrapped.Invoke(owner, new object[7] { t1, t2, t3, t4, t5, t6, t7 });
        }

        public TReturn WrapFunc8<T1, T2, T3, T4, T5, T6, T7, T8, TReturn>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8)
        {
            return (TReturn)wrapped.Invoke(owner, new object[8] { t1, t2, t3, t4, t5, t6, t7, t8 });
        }

        public void WrapAction()
        {
            wrapped.Invoke(owner, new object[0]);
        }

        public void WrapAction1<T1>(T1 t1)
        {
            wrapped.Invoke(owner, new object[1] { t1 });
        }

        public void WrapAction2<T1, T2>(T1 t1, T2 t2)
        {
            wrapped.Invoke(owner, new object[2] { t1, t2 });
        }

        public void WrapAction3<T1, T2, T3>(T1 t1, T2 t2, T3 t3)
        {
            wrapped.Invoke(owner, new object[3] { t1, t2, t3 });
        }

        public void WrapAction4<T1, T2, T3, T4>(T1 t1, T2 t2, T3 t3, T4 t4)
        {
            wrapped.Invoke(owner, new object[4] { t1, t2, t3, t4 });
        }

        public void WrapAction5<T1, T2, T3, T4, T5>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5)
        {
            wrapped.Invoke(owner, new object[5] { t1, t2, t3, t4, t5 });
        }

        public void WrapAction6<T1, T2, T3, T4, T5, T6>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6)
        {
            wrapped.Invoke(owner, new object[6] { t1, t2, t3, t4, t5, t6 });
        }

        public void WrapAction7<T1, T2, T3, T4, T5, T6, T7>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7)
        {
            wrapped.Invoke(owner, new object[7] { t1, t2, t3, t4, t5, t6, t7 });
        }

        public void WrapAction8<T1, T2, T3, T4, T5, T6, T7, T8>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8)
        {
            wrapped.Invoke(owner, new object[8] { t1, t2, t3, t4, t5, t6, t7, t8 });
        }
    }

    internal static class PropertySetterHelper
    {
        public static Action<object, object> BuildSetAccessor(MethodInfo method)
        {
            ParameterExpression instance = Expression.Parameter(typeof(object), "o");
            ParameterExpression value = Expression.Parameter(typeof(object));
            return Expression.Lambda<Action<object, object>>(
                Expression.Call(
                    Expression.Convert(instance, method.DeclaringType),
                    method,
                    Expression.Convert(value, method.GetParameters()[0].ParameterType)),
                instance,
                value).Compile();
        }
    }

    public abstract class ReflectObjectProperties
    {
        private static readonly List<Type> funcTypes = new List<Type>
        {
            typeof(Func<>),
            typeof(Func<,>),
            typeof(Func<,,>),
            typeof(Func<,,,>),
            typeof(Func<,,,,>),
            typeof(Func<,,,,,>),
            typeof(Func<,,,,,,>),
            typeof(Func<,,,,,,,>),
            typeof(Func<,,,,,,,,>),
        };

        private static readonly List<Type> actionTypes = new List<Type>
        {
            typeof(Action),
            typeof(Action<>),
            typeof(Action<,>),
            typeof(Action<,,>),
            typeof(Action<,,,>),
            typeof(Action<,,,,>),
            typeof(Action<,,,,,>),
            typeof(Action<,,,,,,>),
            typeof(Action<,,,,,,,>),
        };

        private static ConcurrentDictionary<Type, List<IPropertySetter>> cache = new ConcurrentDictionary<Type, List<IPropertySetter>>();

        public object ReflectedObject { get; }

        public Type ReflectedType { get; }

        public ReflectObjectProperties()
        {
        }

        public ReflectObjectProperties(object toReflect)
        {
            ReflectedObject = toReflect;
            ReflectedType = toReflect.GetType();
            Type type = GetType();
            cache.GetOrAdd(type, (Type _) => GetOwnSettableProperties().Select(delegate (PropertyInfo ownProperty)
            {
                BindingFlags bindingFlags = GetBindingFlags(ownProperty);
                bool? isAction = FuncActionPropertyCheck(ownProperty.PropertyType);
                return (isAction.HasValue && !FuncActionPropertyIsProperty(ownProperty))
                    ? (IPropertySetter)new MethodSetter(ownProperty, isAction.Value, bindingFlags, ReflectedType)
                    : (IPropertySetter)new PropertySetter(ownProperty, bindingFlags, ReflectedType);
            }).ToList()).ForEach(delegate (IPropertySetter setter)
            {
                setter.Set(this, ReflectedObject);
            });
        }

        private bool FuncActionPropertyIsProperty(PropertyInfo property)
        {
            return property.GetCustomAttribute<DelegatePropertyAttribute>() != null;
        }

        private bool? FuncActionPropertyCheck(Type propertyType)
        {
            if (propertyType == typeof(Action))
            {
                return true;
            }

            if (propertyType.IsGenericType)
            {
                Type genericTypeDefinition = propertyType.GetGenericTypeDefinition();
                if (funcTypes.SingleOrDefault((Type func) => func == genericTypeDefinition) != null)
                {
                    return false;
                }

                if (actionTypes.SingleOrDefault((Type action) => action == genericTypeDefinition) != null)
                {
                    return true;
                }
            }

            return null;
        }

        private BindingFlags GetBindingFlags(PropertyInfo ownProperty)
        {
            BindingFlags result = BindingFlags.Instance | BindingFlags.Public;
            ReflectFlagsAttribute customAttribute = ownProperty.GetCustomAttribute<ReflectFlagsAttribute>();
            if (customAttribute != null)
            {
                result = customAttribute.BindingFlags;
            }

            return result;
        }

        private IEnumerable<PropertyInfo> GetOwnSettableProperties()
        {
            List<string> excludeProperties = new List<string> { "ReflectedObject", "ReflectedType" };
            return from p in GetType().GetProperties()
                   where !excludeProperties.Contains(p.Name)
                   where p.GetCustomAttribute<IgnoreAttribute>() == null
                   select p;
        }

        internal static bool IsReflectObjectPropertiesType(Type type)
        {
            return typeof(ReflectObjectProperties).IsAssignableFrom(type);
        }

        public static void ClearCache()
        {
            cache = new ConcurrentDictionary<Type, List<IPropertySetter>>();
        }

        public static void ClearCache(Type reflectObjectPropertiesType)
        {
            if (cache.ContainsKey(reflectObjectPropertiesType))
            {
                cache.TryRemove(reflectObjectPropertiesType, out _);
            }
        }
    }
}
