// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FineCodeCoverage
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidFCCPackageString = "4e91ba47-cd42-42bc-b92e-3c4355d2eb5f";
        public static Guid guidFCCPackage = new Guid(guidFCCPackageString);

        public const string guidFCCPackageCmdSetString = "d58a999f-4a1b-42df-839a-cb31a0a4fed7";
        public static Guid guidFCCPackageCmdSet = new Guid(guidFCCPackageCmdSetString);

        public const string guidMonikersString = "c07b27ae-9756-4632-a6e6-1578f6dfbedf";
        public static Guid guidMonikers = new Guid(guidMonikersString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int FCCToolsMenuGroup = 0x1020;
        public const int ReportToolWindowToolbar = 0x1021;
        public const int ReadGroup = 0x1022;
        public const int FeedbackGroup = 0x1023;
        public const int ReportDetailsGroup = 0x1024;
        public const int ConfigurationGroup = 0x1025;
        public const int RunGroup = 0x1028;
        public const int cmdidOpenReportWindowCommand = 0x0001;
        public const int cmdidToggleCoverageIndicatorsCommand = 0x0002;
        public const int cmdidClearUICommand = 0x0003;
        public const int cmdidOpenReadMeCommand = 0x0004;
        public const int cmdidOpenFCCGithubCommand = 0x0005;
        public const int cmdidNewIssueCommand = 0x0006;
        public const int cmdidMarketplaceRateAndReviewCommand = 0x0007;
        public const int cmdidOpenFundingCommand = 0x0008;
        public const int cmdidOpenFCCOutputPaneCommand = 0x0009;
        public const int cmdidOpenCoberturaCommand = 0x000A;
        public const int cmdidOpenHotspotsCommand = 0x000B;
        public const int cmdidEditColumnsCommand = 0x000C;
        public const int cmdidShowReportViewCommand = 0x000D;
        public const int cmdidOpenSettingsCommand = 0x000E;
        public const int cmdidResetSettingsCommand = 0x000F;
        public const int cmdidCollectTUnitCommand = 0x0010;
        public const int cmdidCancelCollectTUnitCommand = 0x0011;
        public const int openReportWindowCommandImageIndex = 0x0001;
        public const int clearUICommandImageIndex = 0x0006;
    }
}
