// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FineCodeCoverage
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidFCCPackageString = "4e91ba47-cd42-42bc-b92e-3c4355d2eb5f";
        public static Guid guidFCCPackage = new Guid(guidFCCPackageString);

        public const string guidFCCPackageCmdSetString = "d58a999f-4a1b-42df-839a-cb31a0a4fed7";
        public static Guid guidFCCPackageCmdSet = new Guid(guidFCCPackageCmdSetString);

        public const string guidMonikersString = "c07b27ae-9756-4632-a6e6-1578f6dfbedf";
        public static Guid guidMonikers = new Guid(guidMonikersString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ReportToolWindowToolbar = 0x1021;
        public const int ReportToolWindowToolbarGroup = 0x1022;
        public const int cmdidOpenReportWindowCommand = 0x00FF;
        public const int cmdidClearUICommand = 0x0100;
        public const int cmdidOpenCoberturaCommand = 0x0101;
        public const int cmdidOpenHotspotsCommand = 0x0102;
        public const int cmdidOpenFCCOutputPaneCommand = 0x0103;
        public const int cmdidOpenSettingsCommand = 0x0104;
        public const int cmdidMarketplaceRateAndReviewCommand = 0x0105;
        public const int cmdidOpenFCCGithubCommand = 0x0106;
        public const int cmdidNewIssueCommand = 0x0107;
        public const int cmdidOpenReadMeCommand = 0x0108;
        public const int cmdidOpenFundingCommand = 0x0109;
        public const int cmdidToggleCoverageIndicatorsCommand = 0x010A;
        public const int cmdidEditColumnsCommand = 0x010B;
        public const int cmdidCollectTUnitCommand = 0x010C;
        public const int openReportWindowCommandImageIndex = 0x0001;
        public const int clearUICommandImageIndex = 0x0006;
    }
}
